config/routes.rb
Rails.application.routes.draw do
  resources :scores
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/score.rb
require 'rtesseract'
require "tts"

class Score < ApplicationRecord
before_validation :hey
def pic=(hey)
uploaded_io = params[:person][:picture]
File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
  file.write(uploaded_io.read)
end
end
def hey
image_path = ' path to your image' 

begin
  result = RTesseract.new(image_path).to_s
# create a new instance of the RTesseract class , passing the image path as the parameter.
  self.title=result
  puts result  
rescue => e
  puts "Error : #{e.message}"
end
title.to_file "en", "./public/uploads/weather.mp3"
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: %i[ show edit update destroy ]

  # GET /scores or /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1 or /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores or /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: "Score was successfully created." }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1 or /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: "Score was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1 or /scores/1.json
  def destroy
    @score.destroy!

    respond_to do |format|
      format.html { redirect_to scores_path, notice: "Score was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.expect(score: [ :title, :composer, :pic ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ai Interpreter Score" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scores/_form.html.erb
<%= form_with(model: score) do |form| %>
  <% if score.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :composer, style: "display: block" %>
    <%= form.text_field :composer %>
  </div>

  <div>
    <%= form.label :pic, style: "display: block" %>
    <%= form.text_field :pic %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/_score.html.erb
<div id="<%= dom_id score %>">
  <p>
    <strong>Title:</strong>
    <%= score.title %>
  </p>

  <p>
    <strong>Composer:</strong>
    <%= score.composer %>
  </p>

  <p>
    <strong>Pic:</strong>
    <%= score.pic %>
  </p>

</div>

app/views/scores/edit.html.erb
<% content_for :title, "Editing score" %>

<h1>Editing score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Show this score", @score %> |
  <%= link_to "Back to scores", scores_path %>
</div>

app/views/scores/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Scores" %>

<h1>Scores</h1>

<div id="scores">
  <% @scores.each do |score| %>
    <%= render score %>
    <p>
      <%= link_to "Show this score", score %>
    </p>
  <% end %>
</div>

<%= link_to "New score", new_score_path %>

app/views/scores/new.html.erb
<% content_for :title, "New score" %>

<h1>New score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Back to scores", scores_path %>
</div>

app/views/scores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @score %>

<div>
  <%= link_to "Edit this score", edit_score_path(@score) %> |
  <%= link_to "Back to scores", scores_path %>

  <%= button_to "Destroy this score", @score, method: :delete %>
</div>